# 
# https://docs.travis-ci.com/user/languages/android/
# android only up to trusty
# rust only up to bionic
# dart only up to xenial
#language: dart
dist: focal

env:
  global:
    - CRATE_NAME=audiofinder
    - UBUNTU_VER=LTS_20.04


addons:
  apt:
    packages:
      # additional for clang https://apt.llvm.org for focal (pop!_linux)
      #- lib32stdc++6
      #- lib32gcc1
      #- lib32gcc-s1
      #- libc6-i386
      # clang llvm (focal version 11)
      - libllvm-11-ocaml-dev
      - libllvm11
      - llvm-11
      - llvm-11-dev
      - llvm-11-doc
      - llvm-11-examples
      - llvm-11-runtime
      # clang clan
      - clang-11
      - clang-tools-11
      - clang-11-doc
      - libclang-common-11-dev
      - libclang-11-dev
      - libclang1-11
      - clang-format-11
      - clangd-11
      # normal
      - p7zip-full


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  cargo: true
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.pub-cache"       # flutter

#before_install:
#  - echo y | sdkmanager "ndk-bundle"

before_script:
  - env

before_install:
 - cd $HOME
 - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O $HOME/android-sdk.tgz
 - mkdir -p android
 - unzip android-sdk.tgz -d android/sdk
 - export PATH=$PATH:$HOME/android/sdk/tools:$HOME/android/sdk/tools/bin

install:
  - echo $CRATE_NAME-$target-$TRAVIS_TAG
  # rustup
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.sh
  - sh ./rustup.sh -y
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  # rustup targets
  - source ~/.cargo/env || true  
  - rustup default nightly
  - rustup target add aarch64-linux-android wasm32-unknown-unknown armv7-linux-androideabi i686-linux-android x86_64-linux-android
  - rustup target add aarch64-apple-ios x86_64-apple-ios
  # cargo programs
  - cargo install --force cargo-lipo
  - cargo install --force cargo-make
  - cargo install --force cargo-ndk
  - cargo install --force cargo-flutter
  - cargo install --force wasm-bindgen-cli
  - cargo install --force cbindgen
  - cargo install --force dart-bindgen --features cli

script:
  - cargo make