# 
# https://docs.travis-ci.com/user/languages/android/
# android only up to trusty
# rust up to bionic
language: dart
dist: focal

env:
  global:
    - CRATE_NAME=audiofinder
    - UBUNTU_VER=LTS_20.04


addons:
  apt:
    packages:
      # additional for clang https://apt.llvm.org for focal (pop!_linux)
      #- lib32stdc++6
      #- lib32gcc1
      #- lib32gcc-s1
      #- libc6-i386
      # clang llvm (focal version 10 instead of 11)
      - libllvm-10-ocaml-dev
      - libllvm10
      - llvm-10
      - llvm-10-dev
      - llvm-10-doc
      - llvm-10-examples
      - llvm-10-runtime
      # clang clan
      - clang-10
      - clang-tools-10
      - clang-10-doc
      - libclang-common-10-dev
      - libclang-10-dev
      - libclang1-10
      - clang-format-10
      - clangd-10
      # normal
      - p7zip-full


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  cargo: true
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.pub-cache"       # flutter

#before_install:
#  - echo y | sdkmanager "ndk-bundle"

before_script:
  - env

install:
  - echo $CRATE_NAME-$target-$TRAVIS_TAG
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.sh
  - sh ./rustup.sh -y
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  # rustup
  - source ~/.cargo/env || true  
  - rustup default nightly
  - rustup add aarch64-linux-android wasm32-unknown-unknown armv7-linux-androideabi i686-linux-android x86_64-linux-android
  - cargo install --force cargo-lipo
  - cargo install --force cargo-make
  - cargo install --force cargo-ndk
  - cargo install --force cargo-flutter
  - cargo install --force wasm-bindgen-cli
  - cargo install --force cbindgen
  - cargo install --force dart-bindgen --features cli

script:
  - cargo make